In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
##Dataset
sent=["the glass of milk",
      "the glass of juice",
      "the cup of tea",
      "I am a good boy",
      "I am a good developer",
      "understand the meaning of words",
      "your videos are good"]


In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
## define the Vocabulary size
voc_size=10000

In [7]:
## one_hot representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]

In [8]:
one_hot_repr

[[1633, 8772, 6446, 7434],
 [1633, 8772, 6446, 23],
 [1633, 3025, 6446, 6392],
 [8081, 4137, 5512, 9804, 4562],
 [8081, 4137, 5512, 9804, 1661],
 [2873, 1633, 9948, 6446, 8732],
 [5011, 3855, 277, 9804]]

In [9]:
### word embedding represention
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [11]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)

In [12]:
embedded_docs

array([[   0,    0,    0,    0, 1633, 8772, 6446, 7434],
       [   0,    0,    0,    0, 1633, 8772, 6446,   23],
       [   0,    0,    0,    0, 1633, 3025, 6446, 6392],
       [   0,    0,    0, 8081, 4137, 5512, 9804, 4562],
       [   0,    0,    0, 8081, 4137, 5512, 9804, 1661],
       [   0,    0,    0, 2873, 1633, 9948, 6446, 8732],
       [   0,    0,    0,    0, 5011, 3855,  277, 9804]], dtype=int32)

In [13]:
## feature repersentation
dim=10

In [16]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile(optimizer='adam',loss='mse',metrics=['accuracy'])

In [19]:

model.build(input_shape=(None, sent_length))
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [20]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step


array([[[ 0.04849351,  0.04086396, -0.02868748, -0.03643619,
          0.04201693, -0.03013834, -0.03693943, -0.04145147,
         -0.04159977, -0.04988222],
        [ 0.04849351,  0.04086396, -0.02868748, -0.03643619,
          0.04201693, -0.03013834, -0.03693943, -0.04145147,
         -0.04159977, -0.04988222],
        [ 0.04849351,  0.04086396, -0.02868748, -0.03643619,
          0.04201693, -0.03013834, -0.03693943, -0.04145147,
         -0.04159977, -0.04988222],
        [ 0.04849351,  0.04086396, -0.02868748, -0.03643619,
          0.04201693, -0.03013834, -0.03693943, -0.04145147,
         -0.04159977, -0.04988222],
        [ 0.04641574,  0.03141369, -0.03761629, -0.00095133,
         -0.02490293, -0.00776396,  0.00460093,  0.02588414,
         -0.00767318, -0.02567844],
        [ 0.01549507,  0.01054343,  0.0257789 ,  0.04646888,
         -0.00495696, -0.02035911, -0.01968479, -0.03267949,
          0.02740992, -0.02121134],
        [ 0.00063298, -0.04661012,  0.04689281,  0.0

In [21]:
embedded_docs[0]

array([   0,    0,    0,    0, 1633, 8772, 6446, 7434], dtype=int32)